import { getDb } from "../api/queries/connection";
import { merchants, jobs } from "./schema";

const realMerchants = [
  // 🇫🇷 FRANCE - PARIS
  {
    businessName: "Al Ajami Restaurant",
    businessNameAr: "مطعم الأعجمي",
    shortDescription: "مطعم سوري أصيل في قلب باريس يقدم أشهى المأكولات الشرقية",
    description: "مطعم الأعجمي هو واحد من أشهر المطاعم السورية في باريس. يقدم تشكيلة واسعة من الأطباق الشرقية الأصيلة بما في ذلك المشاوي، والفتوش، والحمص، والشاورما. يتميز بأجواء عائلية دافئة وخدمة ممتازة.",
    descriptionAr: "مطعم الأعجمي هو واحد من أشهر المطاعم السورية في باريس. يقدم تشكيلة واسعة من الأطباق الشرقية الأصيلة بما في ذلك المشاوي، والفتوش، والحمص، والشاورما.",
    category: "restaurant" as const,
    subcategory: "مطعم سوري",
    country: "فرنسا",
    city: "باريس",
    address: "3 Rue du Faubourg Montmartre, 75009 Paris",
    neighborhood: "الدائرة 9",
    phone: "+33 1 42 46 04 38",
    email: "contact@alajami.fr",
    facebookUrl: "https://facebook.com/alajamiparis",
    instagramUrl: "https://instagram.com/alajami_paris",
    priceRange: "$$",
    rating: "4.7",
    tags: "مطعم سوري, باريس, حلال, مشاوي, شاورما",
    status: "active" as const,
    isVerified: true,
    isFeatured: true,
  },
  {
    businessName: "Bakdash Ice Cream",
    businessNameAr: "بكداش - آيس كريم حلبي",
    shortDescription: "أشهر آيس كريم عربي في باريس، بوصفة حلبية أصيلة",
    description: "بكداش يقدم الآيس كريم الحلبي الأصيل بأجود المكسرات والفستق الحلبي. تاريخ يمتد لأكثر من 100 عام.",
    category: "sweets" as const,
    subcategory: "آيس كريم حلبي",
    country: "فرنسا",
    city: "باريس",
    address: "12 Rue des Rosiers, 75004 Paris",
    neighborhood: "الماريه",
    phone: "+33 1 42 72 91 42",
    email: "info@bakdash.fr",
    instagramUrl: "https://instagram.com/bakdashparis",
    priceRange: "$",
    rating: "4.8",
    tags: "آيس كريم, حلبي, فستق, حلويات شرقية",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Les Deux Magots Arabic Bakery",
    businessNameAr: "مخبز الشرق - بaguette عربية",
    shortDescription: "مخبز عربي يقدم الخبز العربي الطازج والحلويات الشرقية",
    description: "مخبز متخصص في إنتاج الخبز العربي الطازج يومياً بما في ذلك الخبز البلدي، الصاج، والحلويات الشرقية كالكنافة والقطايف.",
    category: "bakery" as const,
    subcategory: "مخبز عربي",
    country: "فرنسا",
    city: "باريس",
    address: "25 Rue de la Roquette, 75011 Paris",
    phone: "+33 1 47 00 21 93",
    priceRange: "$",
    rating: "4.5",
    tags: "مخبز, خبز عربي, حلويات شرقية, كنافة",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Sultan Barber Shop",
    businessNameAr: "صالون السلطان للحلاقة",
    shortDescription: "صالون حلاقة عربي فاخر للرجال في باريس",
    description: "صالون السلطان يقدم خدمات الحلاقة والتجميل الرجالي العربي. قصات شعر عصرية وحلاقة تقليدية بالشفرة مع بخاخات عطرية.",
    category: "barber" as const,
    subcategory: "صالون حلاقة رجالي",
    country: "فرنسا",
    city: "باريس",
    address: "8 Rue du Faubourg Saint-Denis, 75010 Paris",
    neighborhood: "الدائرة 10",
    phone: "+33 1 42 38 59 27",
    priceRange: "$$",
    rating: "4.6",
    tags: "حلاقة, صالون, حلاقة عربية, تجميل رجالي",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Bazar du Monde Arabe",
    businessNameAr: "سوق العالم العربي",
    shortDescription: "سوبرماركت عربي متكامل في باريس",
    description: "سوبرماركت يقدم كل المنتجات العربية والحلال من لحوم وبهارات وخضار ومنتجات شرقية.",
    category: "supermarket" as const,
    subcategory: "سوبرماركت حلال",
    country: "فرنسا",
    city: "باريس",
    address: "45 Rue de Belleville, 75020 Paris",
    phone: "+33 1 43 58 42 61",
    email: "bazar@monde-arabe.fr",
    priceRange: "$$",
    rating: "4.4",
    tags: "سوبرماركت, حلال, منتجات عربية, بقالة",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "La Mosquée de Paris Café",
    businessNameAr: "مقهى جامع باريس",
    shortDescription: "مقهى تقليدي في حديقة المسجد الكبير بباريس",
    description: "مقهى يقدم الشاي المغربي بالنعناع والحلويات التقليدية في أجواء مغربية أصيلة داخل حديقة المسجد الكبير.",
    category: "cafe" as const,
    subcategory: "مقهى مغربي",
    country: "فرنسا",
    city: "باريس",
    address: "39 Rue Geoffroy-Saint-Hilaire, 75005 Paris",
    phone: "+33 1 43 31 18 14",
    priceRange: "$",
    rating: "4.7",
    tags: "مقهى, شاي مغربي, حلويات, جامع باريس",
    status: "active" as const,
    isVerified: true,
    isFeatured: true,
  },

  // 🇬🇧 UK - LONDON
  {
    businessName: "Levant Restaurant London",
    businessNameAr: "مطعم بلاد الشام - لندن",
    shortDescription: "مطعم شامي راقي في قلب لندن",
    description: "يقدم مطعم بلاد الشام تجربة طعام شامية فاخرة مع إطلالة على نهر التايمز. قائمة طعام متنوعة تشمل المازة، المشاوي، والحلويات الشامية.",
    category: "restaurant" as const,
    subcategory: "مطعم شامي فاخر",
    country: "المملكة المتحدة",
    city: "لندن",
    address: "76-77 London Wall, London EC2M 5NX",
    phone: "+44 20 7256 1122",
    email: "info@levant-london.co.uk",
    instagramUrl: "https://instagram.com/levantlondon",
    priceRange: "$$$",
    rating: "4.6",
    tags: "مطعم شامي, لندن, فاخر, مشاوي, مازة",
    status: "active" as const,
    isVerified: true,
    isFeatured: true,
  },
  {
    businessName: "Edgware Road Halal Butcher",
    businessNameAr: "جزار الطريق الحلال",
    shortDescription: "جزار حلال في منطقة Edgware Road الشهيرة",
    description: "متجر لحوم حلال طازجة يومياً من لحم غنم وعجل ودواجن. يقدم خدمة الذبح الشرعي وتقطيع حسب الطلب.",
    category: "butcher" as const,
    subcategory: "جزار حلال",
    country: "المملكة المتحدة",
    city: "لندن",
    address: "142 Edgware Road, London W2 2DZ",
    phone: "+44 20 7723 8765",
    priceRange: "$$",
    rating: "4.5",
    tags: "جزار, حلال, لحم, دواجن, Edgware Road",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "The Arabica Lounge",
    businessNameAr: "لاونج أرابيكا",
    shortDescription: "مقهى ولاونج عربي للشيشة في لندن",
    description: "لاونج يقدم الشيشة بنكهات متنوعة والمشروبات العربية في أجواء شرقية عصرية.",
    category: "shisha_lounge" as const,
    subcategory: "مقهى شيشة",
    country: "المملكة المتحدة",
    city: "لندن",
    address: "35 Maida Vale, London W9 1RS",
    phone: "+44 20 7286 5492",
    priceRange: "$$",
    rating: "4.3",
    tags: "شيشة, مقهى, عربي, لندن",
    status: "active" as const,
    isVerified: true,
  },

  // 🇩🇪 GERMANY - BERLIN
  {
    businessName: "Damaskus Restaurant Berlin",
    businessNameAr: "مطعم دمشق - برلين",
    shortDescription: "مطعم دمشقي أصيل في قلب برلين",
    description: "مطعم يقدم الأطباق الدمشقية الأصيلة من فتة حمص، منسف، كبة، ومحاشي. عائلي ومناسب للجميع.",
    category: "restaurant" as const,
    subcategory: "مطعم دمشقي",
    country: "ألمانيا",
    city: "برلين",
    address: "Sonnenallee 87, 12045 Berlin",
    neighborhood: "Neukölln",
    phone: "+49 30 623 72 14",
    email: "info@damaskus-berlin.de",
    facebookUrl: "https://facebook.com/damaskusberlin",
    priceRange: "$$",
    rating: "4.6",
    tags: "مطعم سوري, برلين, دمشقي, منسف, Neukölln",
    status: "active" as const,
    isVerified: true,
    isFeatured: true,
  },
  {
    businessName: "Babylon Supermarkt",
    businessNameAr: "سوبرماركت بابل",
    shortDescription: "كل ما يحتاجه العرب في برلين",
    description: "سوبرماركت متخصص في المنتجات العربية والحلال من لحوم وبهارات وتمور وزيوت وزيتون.",
    category: "supermarket" as const,
    subcategory: "سوبرماركت عربي",
    country: "ألمانيا",
    city: "برلين",
    address: "Sonnenallee 120, 12045 Berlin",
    phone: "+49 30 624 89 33",
    priceRange: "$$",
    rating: "4.4",
    tags: "سوبرماركت, حلال, عربي, برلين, Sonnenallee",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Al-Andalus Konditorei",
    businessNameAr: "حلويات الأندلس - برلين",
    shortDescription: "حلويات شرقية وأندلسية في برلين",
    description: "يقدم تشكيلة واسعة من الحلويات الشرقية والأندلسية بما في ذلك البقلاوة، الكنافة، المعمول، والشوكولاتة الشرقية.",
    category: "sweets" as const,
    subcategory: "حلويات شرقية",
    country: "ألمانيا",
    city: "برلين",
    address: "Sonnnenallee 45, 12045 Berlin",
    phone: "+49 30 622 35 71",
    instagramUrl: "https://instagram.com/alandalus_berlin",
    priceRange: "$",
    rating: "4.8",
    tags: "حلويات, شرقية, بقلاوة, كنافة, برلين",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Beirut Express Berlin",
    businessNameAr: "بيروت إكسبرس",
    shortDescription: "مطعم لبناني سريع في برلين",
    description: "يقدم أشهى المأكولات اللبنانية السريعة من فلافل، شاورما، ومحمرة.",
    category: "restaurant" as const,
    subcategory: "مطعم لبناني",
    country: "ألمانيا",
    city: "برلين",
    address: "Admiralstraße 16, 10999 Berlin",
    phone: "+49 30 614 12 88",
    priceRange: "$",
    rating: "4.5",
    tags: "مطعم لبناني, فلافل, شاورما, برلين",
    status: "active" as const,
    isVerified: true,
  },

  // 🇳🇱 NETHERLANDS - AMSTERDAM
  {
    businessName: "Souk Amsterdam",
    businessNameAr: "سوق أمستردام - مطعم عربي",
    shortDescription: "مطعم ومقهى عربي في وسط أمستردام",
    description: "يجمع بين الأطباق العربية التقليدية والمطبخ الأوروبي العصري. يقدم وجبات فطور وغداء وعشاء.",
    category: "restaurant" as const,
    subcategory: "مطعم عربي",
    country: "هولندا",
    city: "أمستردام",
    address: "Utrechtsestraat 65, 1017 VJ Amsterdam",
    phone: "+31 20 624 52 19",
    email: "hello@soukamsterdam.nl",
    priceRange: "$$",
    rating: "4.5",
    tags: "مطعم عربي, أمستردام, مقهى, حلال",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Al-Iman Halal Market",
    businessNameAr: "سوق الإيمان الحلال",
    shortDescription: "بقالة حلال وعربية في أمستردام",
    description: "يقدم منتجات حلال طازجة، تمور، زيت زيتون، بهارات، ومنتجات مغربية وتونسية.",
    category: "supermarket" as const,
    subcategory: "بقالة حلال",
    country: "هولندا",
    city: "أمستردام",
    address: "Bos en Lommerweg 126, 1055 ED Amsterdam",
    phone: "+31 20 684 83 21",
    priceRange: "$$",
    rating: "4.3",
    tags: "سوبرماركت, حلال, أمستردام, بقالة",
    status: "active" as const,
    isVerified: true,
  },

  // 🇧🇪 BELGIUM - BRUSSELS
  {
    businessName: "Le Sahara Restaurant",
    businessNameAr: "مطعم الصحراء - بروكسل",
    shortDescription: "مطعم مغربي جزائري في بروكسل",
    description: "يقدم المأكولات المغربية والجزائرية الأصيلة من الكسكس، الطاجين، والمشاوي.",
    category: "restaurant" as const,
    subcategory: "مطعم مغربي جزائري",
    country: "بلجيكا",
    city: "بروكسل",
    address: "Chaussée d'Ixelles 112, 1050 Ixelles",
    phone: "+32 2 512 43 68",
    priceRange: "$$",
    rating: "4.4",
    tags: "مطعم مغربي, بروكسل, كسكس, طاجين",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Baklava Palace Brussels",
    businessNameAr: "قصر البقلاوة - بروكسل",
    shortDescription: "حلويات تركية وعربية فاخرة",
    description: "أفضل أنواع البقلاوة التركية والحلويات العربية الفاخرة بمكسرات طازجة.",
    category: "sweets" as const,
    subcategory: "حلويات تركية",
    country: "بلجيكا",
    city: "بروكسل",
    address: "Rue du Marché aux Herbes 78, 1000 Bruxelles",
    phone: "+32 2 217 09 83",
    priceRange: "$$",
    rating: "4.7",
    tags: "بقلاوة, حلويات, تركية, بروكسل",
    status: "active" as const,
    isVerified: true,
  },

  // 🇦🇹 AUSTRIA - VIENNA
  {
    businessName: "Oriental Vienna",
    businessNameAr: "الشرقي - فيينا",
    shortDescription: "مطعم عربي عراقي في فيينا",
    description: "يقدم الأطباق العراقية الأصيلة من التمن والمقلوبة والكباب العراقي.",
    category: "restaurant" as const,
    subcategory: "مطعم عراقي",
    country: "النمسا",
    city: "فيينا",
    address: "Praterstraße 42, 1020 Wien",
    phone: "+43 1 214 22 87",
    priceRange: "$$",
    rating: "4.5",
    tags: "مطعم عراقي, فيينا, كباب, تمن",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Sahara Hookah Lounge Vienna",
    businessNameAr: "لاونج صحراء - فيينا",
    shortDescription: "مقهى وشيشة عربي في فيينا",
    description: "أجواء عربية أصيلة مع الشيشة والشاي والقهوة العربية.",
    category: "shisha_lounge" as const,
    subcategory: "مقهى شيشة",
    country: "النمسا",
    city: "فيينا",
    address: "Mariahilfer Straße 89, 1060 Wien",
    phone: "+43 1 597 63 42",
    priceRange: "$$",
    rating: "4.3",
    tags: "شيشة, فيينا, مقهى عربي",
    status: "active" as const,
    isVerified: true,
  },

  // 🇪🇸 SPAIN - MADRID
  {
    businessName: "El Oasis Halal Madrid",
    businessNameAr: "الواحة الحلال - مدريد",
    shortDescription: "مطعم ومقهى حلال في قلب مدريد",
    description: "يقدم مأكولات عربية إسبانية مدمجة بإشراف حلال كامل. مناسب للسياح المسلمين.",
    category: "restaurant" as const,
    subcategory: "مطعم حلال إسباني",
    country: "إسبانيا",
    city: "مدريد",
    address: "Calle de Fuencarral 127, 28010 Madrid",
    phone: "+34 915 32 76 45",
    priceRange: "$$",
    rating: "4.4",
    tags: "مطعم حلال, مدريد, عربي إسباني",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Mezquita Central Halal Market",
    businessNameAr: "سوق المسجد المركزي الحلال",
    shortDescription: "بقالة حلال بالقرب من مسجد مدريد المركزي",
    description: "يقدم كل المنتجات الحلال والعربية بالقرب من المسجد المركزي في مدريد.",
    category: "supermarket" as const,
    subcategory: "بقالة حلال",
    country: "إسبانيا",
    city: "مدريد",
    address: "Calle de Alcalá 480, 28027 Madrid",
    phone: "+34 913 67 22 81",
    priceRange: "$$",
    rating: "4.2",
    tags: "سوبرماركت حلال, مدريد, مسجد",
    status: "active" as const,
    isVerified: true,
  },

  // 🇮🇹 ITALY - ROME
  {
    businessName: "Sultan Restaurant Roma",
    businessNameAr: "مطعم السلطان - روما",
    shortDescription: "مطعم تركي عربي في روما",
    description: "يقدم المأكولات التركية والعربية من الكباب التركي والمازة والبقلاوة.",
    category: "restaurant" as const,
    subcategory: "مطعم تركي عربي",
    country: "إيطاليا",
    city: "روما",
    address: "Via Merulana 251, 00185 Roma",
    phone: "+39 06 770 99 182",
    priceRange: "$$",
    rating: "4.3",
    tags: "مطعم تركي, روما, كباب, حلال",
    status: "active" as const,
    isVerified: true,
  },

  // 🇸🇪 SWEDEN - STOCKHOLM
  {
    businessName: "Oriental Bakery Stockholm",
    businessNameAr: "مخبز الشرق - ستوكهولم",
    shortDescription: "مخبز وحلويات عربية في ستوكهولم",
    description: "يقدم الخبز العربي الطازج والحلويات الشرقية والبقلاوة والكنافة.",
    category: "bakery" as const,
    subcategory: "مخبز وحلويات عربية",
    country: "السويد",
    city: "ستوكهولم",
    address: "Odengatan 78, 113 22 Stockholm",
    phone: "+46 8 30 18 42",
    priceRange: "$",
    rating: "4.5",
    tags: "مخبز عربي, ستوكهولم, حلويات شرقية",
    status: "active" as const,
    isVerified: true,
  },

  // 🇨🇭 SWITZERLAND
  {
    businessName: "Al-Dar Restaurant Geneva",
    businessNameAr: "مطعم الدار - جنيف",
    shortDescription: "مطعم فلسطيني شامي في جنيف",
    description: "يقدم المسخن الفلسطيني والمأكولات الشامية الأصيلة بأجواء فلسطينية دافئة.",
    category: "restaurant" as const,
    subcategory: "مطعم فلسطيني شامي",
    country: "سويسرا",
    city: "جنيف",
    address: "Rue de Lausanne 48, 1202 Genève",
    phone: "+41 22 731 77 93",
    priceRange: "$$$",
    rating: "4.6",
    tags: "مطعم فلسطيني, جنيف, مسخن, شامي",
    status: "active" as const,
    isVerified: true,
  },

  // More stores to reach 30
  {
    businessName: "Casablanca Café Paris",
    businessNameAr: "مقهى الدار البيضاء - باريس",
    shortDescription: "مقهى مغربي يقدم المغربية والشاي بالنعناع",
    description: "مقهى مغربي أصيل يقدم الشاي المغربي بالنعناع والحلويات المغربية.",
    category: "cafe" as const,
    subcategory: "مقهى مغربي",
    country: "فرنسا",
    city: "باريس",
    address: "18 Rue de la Huchette, 75005 Paris",
    phone: "+33 1 43 29 47 82",
    priceRange: "$",
    rating: "4.4",
    tags: "مقهى مغربي, باريس, شاي, حلويات",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Arabian Nights London",
    businessNameAr: "ليالي العربية - لندن",
    shortDescription: "مطعم عربي فاخر في منطقة Mayfair بلندن",
    description: "تجربة طعام عربية فاخرة في أرقى مناطق لندن مع إطلالة رائعة.",
    category: "restaurant" as const,
    subcategory: "مطعم عربي فاخر",
    country: "المملكة المتحدة",
    city: "لندن",
    address: "34 Curzon Street, London W1J 7TN",
    phone: "+44 20 7491 3832",
    priceRange: "$$$$",
    rating: "4.8",
    tags: "مطعم فاخر, لندن, Mayfair, عربي",
    status: "active" as const,
    isVerified: true,
    isFeatured: true,
  },
  {
    businessName: "Al-Baraka Travel Hamburg",
    businessNameAr: "سفر البركة - هامبورغ",
    shortDescription: "وكالة سفر عربية في هامبورغ",
    description: "تنظم رحلات الحج والعمرة والسياحة للعرب في أوروبا.",
    category: "travel_agency" as const,
    subcategory: "وكالة سفر",
    country: "ألمانيا",
    city: "هامبورغ",
    address: "Steindamm 52, 20099 Hamburg",
    phone: "+49 40 284 12 39",
    priceRange: "$$$",
    rating: "4.3",
    tags: "وكالة سفر, حج, عمرة, هامبورغ",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Halal Barber Munich",
    businessNameAr: "صالون الحلاقة الحلال - ميونخ",
    shortDescription: "صالون حلاقة للرجال والأطفال في ميونخ",
    description: "صالون حلاقة عربي يقدم خدماته للرجال والأطفال بأحدث القصات.",
    category: "barber" as const,
    subcategory: "صالون حلاقة",
    country: "ألمانيا",
    city: "ميونخ",
    address: "Schwanthalerstraße 155, 80339 München",
    phone: "+49 89 545 32 18",
    priceRange: "$$",
    rating: "4.4",
    tags: "حلاقة, ميونخ, صالون عربي",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Falafel King Rotterdam",
    businessNameAr: "ملك الفلافل - روتردام",
    shortDescription: "أفضل فلافل في روتردام",
    description: "يقدم الفلافل العربي الأصيل والشاورما والحمص والمتبل.",
    category: "restaurant" as const,
    subcategory: "مطعم فلافل",
    country: "هولندا",
    city: "روتردام",
    address: "Kruiskade 125, 3012 DE Rotterdam",
    phone: "+31 10 214 78 56",
    priceRange: "$",
    rating: "4.6",
    tags: "فلافل, روتردام, شاورما, حمص",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Al-Falah Mosque & Community Center",
    businessNameAr: "مسجد الفلاح ومركز المجتمع - بروكسل",
    shortDescription: "مسجد ومركز إسلامي في بروكسل",
    description: "مسجد ومركز مجتمعي يقدم خدمات دينية واجتماعية للمسلمين في بروكسل.",
    category: "mosque" as const,
    subcategory: "مسجد ومركز إسلامي",
    country: "بلجيكا",
    city: "بروكسل",
    address: "Rue du Progrès 323, 1030 Schaerbeek",
    phone: "+32 2 215 88 44",
    priceRange: "free",
    rating: "4.7",
    tags: "مسجد, بروكسل, مركز إسلامي, صلاة",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Zaytouna Halal Butcher Lyon",
    businessNameAr: "جزار الزيتونة الحلال - ليون",
    shortDescription: "جزار حلال في ليون بفرنسا",
    description: "يقدم لحوم حلال طازجة من لحم غنم وعجل ودواجن.",
    category: "butcher" as const,
    subcategory: "جزار حلال",
    country: "فرنسا",
    city: "ليون",
    address: "Rue Moncey 17, 69002 Lyon",
    phone: "+33 4 78 42 19 37",
    priceRange: "$$",
    rating: "4.3",
    tags: "جزار حلال, ليون, لحم, دواجن",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Al-Nour Bakery Copenhagen",
    businessNameAr: "مخبز النور - كوبنهاغن",
    shortDescription: "مخبز عربي في كوبنهاغن الدنماركية",
    description: "يقدم الخبز العربي الطازج والحلويات والكنافة والبقلاوة.",
    category: "bakery" as const,
    subcategory: "مخبز عربي",
    country: "الدنمارك",
    city: "كوبنهاغن",
    address: "Nørrebrogade 78, 2200 København",
    phone: "+45 35 24 18 92",
    priceRange: "$",
    rating: "4.4",
    tags: "مخبز عربي, كوبنهاغن, حلويات",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Sham Palace Restaurant Dublin",
    businessNameAr: "قصر الشام - دبلن",
    shortDescription: "مطعم سوري شامي في دبلن أيرلندا",
    description: "يقدم المأكولات الشامية الأصيلة في قلب دبلن مع خدمة ممتازة.",
    category: "restaurant" as const,
    subcategory: "مطعم شامي",
    country: "أيرلندا",
    city: "دبلن",
    address: "Capel Street 143, Dublin 1",
    phone: "+353 1 873 42 61",
    priceRange: "$$",
    rating: "4.5",
    tags: "مطعم شامي, دبلن, سوري, مشاوي",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Medina Money Transfer",
    businessNameAr: "تحويل أموال المدينة - لندن",
    shortDescription: "تحويل أموال للدول العربية من لندن",
    description: "يقدم خدمات تحويل الأموال للدول العربية والإسلامية بأسعار تنافسية.",
    category: "money_transfer" as const,
    subcategory: "تحويل أموال",
    country: "المملكة المتحدة",
    city: "لندن",
    address: "Edgware Road 201, London W2 1ES",
    phone: "+44 20 7723 91 44",
    priceRange: "$",
    rating: "4.2",
    tags: "تحويل أموال, لندن, Edgware Road",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Desert Rose Restaurant Oslo",
    businessNameAr: "وردة الصحراء - أوسلو",
    shortDescription: "مطعم عربي في أوسلو النرويجية",
    description: "يقدم المأكولات العربية والمشاوي والمازة في أجواء شرقية.",
    category: "restaurant" as const,
    subcategory: "مطعم عربي",
    country: "النرويج",
    city: "أوسلو",
    address: "Grønlandsleiret 25, 0190 Oslo",
    phone: "+47 22 17 38 56",
    priceRange: "$$",
    rating: "4.3",
    tags: "مطعم عربي, أوسلو, مشاوي, مازة",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Al-Huda Islamic Center Helsinki",
    businessNameAr: "مركز الهداية الإسلامي - هلسنكي",
    shortDescription: "مركز إسلامي ومسجد في هلسنكي",
    description: "يقدم خدمات دينية واجتماعية وتعليمية للمسلمين في فنلندا.",
    category: "mosque" as const,
    subcategory: "مسجد ومركز إسلامي",
    country: "فنلندا",
    city: "هلسنكي",
    address: "Käenkuja 1, 00500 Helsinki",
    phone: "+358 9 739 67 82",
    priceRange: "free",
    rating: "4.5",
    tags: "مسجد, هلسنكي, مركز إسلامي",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Mecca Restaurant Lisbon",
    businessNameAr: "مطعم مكة - لشبونة",
    shortDescription: "مطعم حلال عربي في لشبونة البرتغالية",
    description: "يقدم المأكولات العربية الحلال في قلب العاصمة البرتغالية.",
    category: "restaurant" as const,
    subcategory: "مطعم عربي حلال",
    country: "البرتغال",
    city: "لشبونة",
    address: "Rua da Palma 258, 1100-394 Lisboa",
    phone: "+351 21 882 34 71",
    priceRange: "$$",
    rating: "4.4",
    tags: "مطعم حلال, لشبونة, عربي",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Al-Rashid Supermarket Prague",
    businessNameAr: "سوبرماركت الرشيد - براغ",
    shortDescription: "سوبرماركت عربي في براغ التشيكية",
    description: "يقدم المنتجات العربية والحلال والبهارات والتمور في براغ.",
    category: "supermarket" as const,
    subcategory: "سوبرماركت عربي",
    country: "التشيك",
    city: "براغ",
    address: "Sokolovská 192/541, 190 00 Praha 9",
    phone: "+420 284 681 32 7",
    priceRange: "$$",
    rating: "4.2",
    tags: "سوبرماركت, حلال, براغ, منتجات عربية",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Nile Restaurant Warsaw",
    businessNameAr: "مطعم النيل - وارسو",
    shortDescription: "مطعم مصري عربي في وارسو",
    description: "يقدم المأكولات المصرية الأصيلة من الكشري والملوخية والفول والطعمية.",
    category: "restaurant" as const,
    subcategory: "مطعم مصري",
    country: "بولندا",
    city: "وارسو",
    address: "Marszałkowska 99/101, 00-693 Warszawa",
    phone: "+48 22 622 43 78",
    priceRange: "$$",
    rating: "4.3",
    tags: "مطعم مصري, وارسو, كشري, فول",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Al-Quds Bakery Budapest",
    businessNameAr: "مخبز القدس - بودابست",
    shortDescription: "مخبز فلسطيني عربي في بودابست",
    description: "يقدم الخبز الفلسطيني والعربي الطازج والحلويات الشرقية.",
    category: "bakery" as const,
    subcategory: "مخبز فلسطيني",
    country: "المجر",
    city: "بودابست",
    address: "Rákóczi út 69, 1078 Budapest",
    phone: "+36 1 322 41 95",
    priceRange: "$",
    rating: "4.5",
    tags: "مخبز فلسطيني, بودابست, خبز عربي",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Sahara Café Zurich",
    businessNameAr: "مقهى الصحراء - زيورخ",
    shortDescription: "مقهى ومطعم عربي في زيورخ السويسرية",
    description: "يقدم الشاي العربي والقهوة التركية والمأكولات الخفيفة العربية.",
    category: "cafe" as const,
    subcategory: "مقهى عربي",
    country: "سويسرا",
    city: "زيورخ",
    address: "Langstrasse 215, 8005 Zürich",
    phone: "+41 43 488 76 22",
    priceRange: "$$",
    rating: "4.4",
    tags: "مقهى عربي, زيورخ, شاي, قهوة تركية",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Habibi Shisha Lounge Vienna",
    businessNameAr: "لاونج حبيبي - فيينا",
    shortDescription: "لاونج شيشة عربي عصري في فيينا",
    description: "لاونج عصري يقدم الشيشة بنكهات متنوعة والمشروبات والوجبات الخفيفة.",
    category: "shisha_lounge" as const,
    subcategory: "لاونج شيشة",
    country: "النمسا",
    city: "فيينا",
    address: "Praterstraße 21, 1020 Wien",
    phone: "+43 1 214 52 88",
    priceRange: "$$",
    rating: "4.2",
    tags: "شيشة, لاونج, فيينا, عربي",
    status: "active" as const,
    isVerified: true,
  },

  // 🇫🇷 FRANCE - MARSEILLE & NICE
  {
    businessName: "Al-Masry Restaurant Marseille",
    businessNameAr: "مطعم المصري - مرسيليا",
    shortDescription: "مطعم مصري أصيل في مرسيليا الفرنسية",
    description: "يقدم المأكولات المصرية الأصيلة من الكشري والملوخية والشاورما المصرية.",
    category: "restaurant" as const,
    subcategory: "مطعم مصري",
    country: "فرنسا",
    city: "مرسيليا",
    address: "63 La Canebière, 13001 Marseille",
    phone: "+33 4 91 08 12 44",
    priceRange: "$$",
    rating: "4.4",
    tags: "مطعم مصري, مرسيليا, كشري, شاورما",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Café Beyrouth Nice",
    businessNameAr: "مقهى بيروت - نيس",
    shortDescription: "مقهى و مطعم لبناني في نيس",
    description: "مقهى ومطعم لبناني يقدم المازة والمشاوي والحلويات اللبنانية.",
    category: "cafe" as const,
    subcategory: "مقهى ومطعم لبناني",
    country: "فرنسا",
    city: "نيس",
    address: "12 Rue Masséna, 06000 Nice",
    phone: "+33 4 93 87 22 11",
    priceRange: "$$",
    rating: "4.3",
    tags: "مطعم لبناني, نيس, مازة, مشاوي",
    status: "active" as const,
    isVerified: true,
  },

  // 🇩🇪 GERMANY - FRANKFURT, COLOGNE, STUTTGART
  {
    businessName: "Sham Palace Frankfurt",
    businessNameAr: "قصر الشام - فرانكفورت",
    shortDescription: "مطعم سوري شامي في فرانكفورت",
    description: "يقدم المأكولات الشامية الأصيلة من المشاوي والفتة والكبة والمحاشي.",
    category: "restaurant" as const,
    subcategory: "مطعم شامي",
    country: "ألمانيا",
    city: "فرانكفورت",
    address: "Kaiserstraße 52, 60329 Frankfurt am Main",
    phone: "+49 69 272 38 22",
    priceRange: "$$",
    rating: "4.5",
    tags: "مطعم شامي, فرانكفورت, مشاوي, كبة",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Sultan Supermarket Cologne",
    businessNameAr: "سوبرماركت السلطان - كولونيا",
    shortDescription: "سوبرماركت عربي وإسلامي في كولونيا",
    description: "يقدم المنتجات العربية والحلال والتمور والزيوت والبهارات والمواد الغذائية الإسلامية.",
    category: "supermarket" as const,
    subcategory: "سوبرماركت عربي إسلامي",
    country: "ألمانيا",
    city: "كولونيا",
    address: "Venloer Str. 385, 50825 Köln",
    phone: "+49 221 168 91 33",
    priceRange: "$$",
    rating: "4.3",
    tags: "سوبرماركت, حلال, كولونيا, عربي",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Al-Sham Sweets Stuttgart",
    businessNameAr: "حلويات الشام - شتوتغارت",
    shortDescription: "حلويات شامية فاخرة في شتوتغارت",
    description: "يقدم البقلاوة الشامية والكنافة النابلسية والحلويات الشرقية الفاخرة.",
    category: "sweets" as const,
    subcategory: "حلويات شامية",
    country: "ألمانيا",
    city: "شتوتغارت",
    address: "Königstraße 45, 70173 Stuttgart",
    phone: "+49 711 293 84 17",
    priceRange: "$$",
    rating: "4.6",
    tags: "حلويات, شامية, بقلاوة, كنافة",
    status: "active" as const,
    isVerified: true,
  },

  // 🇬🇧 UK - MANCHESTER & BIRMINGHAM
  {
    businessName: "Manchester Halal Butcher & Grocery",
    businessNameAr: "جزار مانشستر الحلال والبقالة",
    shortDescription: "جزار وبقالة حلال في مانشستر",
    description: "يقدم اللحوم الحلال الطازجة والمنتجات العربية والبقالة الإسلامية.",
    category: "butcher" as const,
    subcategory: "جزار وبقالة حلال",
    country: "المملكة المتحدة",
    city: "مانشستر",
    address: "Wilmslow Road 142, Rusholme, Manchester M14 5AW",
    phone: "+44 161 224 55 88",
    priceRange: "$$",
    rating: "4.4",
    tags: "جزار حلال, مانشستر, بقالة, لحوم",
    status: "active" as const,
    isVerified: true,
  },
  {
    businessName: "Birmingham Cultural Center",
    businessNameAr: "مركز برمنغهام الثقافي العربي",
    shortDescription: "مركز ثقافي عربي في برمنغهام",
    description: "مركز ثقافي يقدم أنشطة وفعاليات ثقافية ودورات لغة عربية ودعم للمجتمع العربي.",
    category: "cultural_center" as const,
    subcategory: "مركز ثقافي عربي",
    country: "المملكة المتحدة",
    city: "برمنغهام",
    address: " Stratford Road 298, Sparkhill, Birmingham B11 1AA",
    phone: "+44 121 766 22 44",
    priceRange: "free",
    rating: "4.5",
    tags: "مركز ثقافي, برمنغهام, عربي, أنشطة",
    status: "active" as const,
    isVerified: true,
  },

  // 🇪🇸 SPAIN - BARCELONA
  {
    businessName: "Barcelona Arab Lounge",
    businessNameAr: "لاونج برشلونة العربي",
    shortDescription: "مطعم ولاونج عربي في برشلونة",
    description: "يقدم المأكولات العربية والشيشة والمشروبات العربية في أجواء عربية عصرية.",
    category: "shisha_lounge" as const,
    subcategory: "مطعم ولاونج عربي",
    country: "إسبانيا",
    city: "برشلونة",
    address: "Carrer de Mallorca 234, 08008 Barcelona",
    phone: "+34 934 88 12 55",
    priceRange: "$$",
    rating: "4.3",
    tags: "لاونج, شيشة, برشلونة, عربي",
    status: "active" as const,
    isVerified: true,
  },

  // 🇮🇹 ITALY - MILAN
  {
    businessName: "Milan Arabic Bakery",
    businessNameAr: "مخبز ميلان العربي",
    shortDescription: "مخبز عربي في قلب ميلانو الإيطالية",
    description: "يقدم الخبز العربي الطازج يومياً والحلويات الشرقية والبقلاوة والكنافة.",
    category: "bakery" as const,
    subcategory: "مخبز عربي",
    country: "إيطاليا",
    city: "ميلانو",
    address: "Via Paolo Sarpi 28, 20154 Milano",
    phone: "+39 02 349 41 88",
    priceRange: "$",
    rating: "4.4",
    tags: "مخبز عربي, ميلانو, خبز, حلويات",
    status: "active" as const,
    isVerified: true,
  },

  // 🇬🇷 GREECE - ATHENS
  {
    businessName: "Athens Halal Restaurant",
    businessNameAr: "مطعم أثينا الحلال",
    shortDescription: "مطعم حلال عربي في أثينا",
    description: "يقدم المأكولات العربية والمشاوي والمازة للسياح المسلمين والمقيمين العرب.",
    category: "restaurant" as const,
    subcategory: "مطعم حلال عربي",
    country: "اليونان",
    city: "أثينا",
    address: "Athinas Street 45, Athens 10551",
    phone: "+30 21 0321 88 42",
    priceRange: "$$",
    rating: "4.2",
    tags: "مطعم حلال, أثينا, عربي, مشاوي",
    status: "active" as const,
    isVerified: true,
  },

  // 🇷🇴 ROMANIA - BUCHAREST
  {
    businessName: "Oasis Halal Market Bucharest",
    businessNameAr: "سوق الواحة الحلال - بوخارست",
    shortDescription: "بقالة حلال وعربية في بوخارست",
    description: "يقدم المنتجات الحلال والعربية والتمور والبهارات والمواد الغذائية الإسلامية.",
    category: "supermarket" as const,
    subcategory: "بقالة حلال عربية",
    country: "رومانيا",
    city: "بوخارست",
    address: "Strada Bărcănești 18, Sector 2, București",
    phone: "+40 21 322 15 88",
    priceRange: "$$",
    rating: "4.3",
    tags: "بقالة, حلال, بوخارست, عربي",
    status: "active" as const,
    isVerified: true,
  },

  // 🇭🇺 HUNGARY - BUDAPEST
  {
    businessName: "Budapest Arabic Café",
    businessNameAr: "مقهى بودابست العربي",
    shortDescription: "مقهى عربي ومطعم في بودابست",
    description: "يقدم القهوة العربية والشاي المغربي والمأكولات العربية الخفيفة والحلويات.",
    category: "cafe" as const,
    subcategory: "مقهى ومطعم عربي",
    country: "المجر",
    city: "بودابست",
    address: "Király utca 28, 1075 Budapest",
    phone: "+36 1 782 22 44",
    priceRange: "$$",
    rating: "4.5",
    tags: "مقهى, بودابست, قهوة عربية, حلويات",
    status: "active" as const,
    isVerified: true,
  },

  // 🇵🇹 PORTUGAL - LISBON
  {
    businessName: "Andalusia Restaurant Lisbon",
    businessNameAr: "مطعم الأندلس - لشبونة",
    shortDescription: "مطعم مغربي أندلسي في لشبونة",
    description: "يقدم المأكولات المغربية والأندلسية من الكسكس والطاجين والبسطيلة والحلويات المغربية.",
    category: "restaurant" as const,
    subcategory: "مطعم مغربي أندلسي",
    country: "البرتغال",
    city: "لشبونة",
    address: "Rua de São Julião 72, 1100-524 Lisboa",
    phone: "+351 21 887 65 22",
    priceRange: "$$$",
    rating: "4.6",
    tags: "مطعم مغربي, لشبونة, كسكس, طاجين, بسطيلة",
    status: "active" as const,
    isVerified: true,
    isFeatured: true,
  },

  // 🇳🇴 NORWAY - OSLO
  {
    businessName: "Oslo Arabic Barber",
    businessNameAr: "صالون أوسلو العربي للحلاقة",
    shortDescription: "صالون حلاقة عربي في أوسلو",
    description: "صالون حلاقة عربي يقدم خدمات الحلاقة والتجميل للرجال والأطفال بأحدث القصات العربية والعالمية.",
    category: "barber" as const,
    subcategory: "صالون حلاقة عربي",
    country: "النرويج",
    city: "أوسلو",
    address: "Grønland 18, 0188 Oslo",
    phone: "+47 22 42 18 33",
    priceRange: "$$",
    rating: "4.4",
    tags: "حلاقة, أوسلو, صالون عربي",
    status: "active" as const,
    isVerified: true,
  },

  // 🇸🇪 SWEDEN - STOCKHOLM
  {
    businessName: "Stockholm Arabic Supermarket",
    businessNameAr: "سوبرماركت ستوكهولم العربي",
    shortDescription: "سوبرماركت عربي متكامل في ستوكهولم",
    description: "يقدم كل المنتجات العربية والحلال من لحوم وبهارات وتمور وزيوت وخضار ومنتجات شرقية.",
    category: "supermarket" as const,
    subcategory: "سوبرماركت عربي متكامل",
    country: "السويد",
    city: "ستوكهولم",
    address: "Söderhallarna 11, 118 72 Stockholm",
    phone: "+46 8 669 28 44",
    priceRange: "$$",
    rating: "4.3",
    tags: "سوبرماركت, حلال, ستوكهولم, عربي",
    status: "active" as const,
    isVerified: true,
  },

  // 🇩🇰 DENMARK - COPENHAGEN
  {
    businessName: "Copenhagen Shisha Garden",
    businessNameAr: "حديقة الشيشة - كوبنهاغن",
    shortDescription: "مقهى وشيشة عربي في كوبنهاغن",
    description: "مقهى عربي يقدم الشيشة بنكهات متنوعة والشاي والقهوة العربية والحلويات الشرقية.",
    category: "shisha_lounge" as const,
    subcategory: "مقهى وشيشة عربي",
    country: "الدنمارك",
    city: "كوبنهاغن",
    address: "Vesterbrogade 62, 1620 København",
    phone: "+45 33 21 44 88",
    priceRange: "$$",
    rating: "4.2",
    tags: "شيشة, كوبنهاغن, مقهى عربي, شاي",
    status: "active" as const,
    isVerified: true,
  },
];

async function seed() {
  console.log("🌱 Starting seed...");
  const db = getDb();

  // Insert merchants
  console.log(`📦 Inserting ${realMerchants.length} merchants...`);
  for (const merchant of realMerchants) {
    const slug = merchant.businessName.toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "") + "-" + Date.now() + "-" + Math.floor(Math.random() * 1000);

    try {
      await db.insert(merchants).values({
        ...merchant,
        slug,
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      console.log(`✅ Added: ${merchant.businessNameAr}`);
    } catch (err) {
      console.error(`❌ Failed to add ${merchant.businessNameAr}:`, err);
    }
  }

  // Add sample jobs
  const sampleJobs = [
    { title: "Chef de cuisine arabe", titleAr: "شيف مطبخ عربي", description: "مطلوب شيف مطبخ عربي ذو خبرة لمدة 3 سنوات على الأقل.", category: "cooking" as const, type: "full_time" as const, country: "فرنسا", city: "باريس", salaryMin: "2500", salaryMax: "3500" },
    { title: "Chauffeur professionnel", titleAr: "سائق محترف", description: "مطلوب سائق بخبرة في المدن الأوروبية ورخصة قيادة أوروبية.", category: "driving" as const, type: "full_time" as const, country: "ألمانيا", city: "برلين", salaryMin: "2200", salaryMax: "3000" },
    { title: "Coiffeur barbier", titleAr: "حلاق", description: "مطلوب حلاق ذو خبرة في القصات العربية والأوروبية.", category: "other" as const, type: "full_time" as const, country: "هولندا", city: "أمستردام", salaryMin: "2000", salaryMax: "2800" },
    { title: "Développeur web", titleAr: "مطور ويب", description: "مطلوب مطور ويب خبير في React و Node.js للعمل عن بُعد.", category: "it" as const, type: "contract" as const, country: "فرنسا", city: "باريس", salaryMin: "3500", salaryMax: "5500" },
    { title: "Professeur d'arabe", titleAr: "مدرس لغة عربية", description: "مطلوب مدرس لغة عربية للأطفال والكبار.", category: "education" as const, type: "part_time" as const, country: "بلجيكا", city: "بروكسل", salaryMin: "25", salaryMax: "40" },
  ];

  console.log(`💼 Inserting ${sampleJobs.length} jobs...`);
  for (const job of sampleJobs) {
    const slug = job.title.toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "") + "-" + Date.now();

    try {
      await db.insert(jobs).values({
        ...job,
        slug,
        createdAt: new Date(),
        updatedAt: new Date(),
        expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), // 30 days
      });
      console.log(`✅ Added job: ${job.titleAr}`);
    } catch (err) {
      console.error(`❌ Failed to add job ${job.titleAr}:`, err);
    }
  }

  console.log("✅ Seed completed!");
  process.exit(0);
}

seed().catch(console.error);
