import { createRouter, publicQuery } from "./middleware";
import { getDb } from "./queries/connection";
import { merchants } from "../db/schema";
import { sql } from "drizzle-orm";

const merchantsData = [
  { businessName: "Al Ajami Restaurant", businessNameAr: "مطعم الأعجمي", shortDescription: "مطعم سوري أصيل في قلب باريس", description: "مطعم الأعجمي هو واحد من أشهر المطاعم السورية في باريس.", category: "restaurant", subcategory: "مطعم سوري", country: "فرنسا", city: "باريس", address: "3 Rue du Faubourg Montmartre, 75009 Paris", phone: "+33 1 42 46 04 38", email: "contact@alajami.fr", priceRange: "$$", rating: "4.7", tags: "مطعم سوري, باريس, حلال, مشاوي", status: "active", isVerified: true, isFeatured: true },
  { businessName: "Bakdash Ice Cream", businessNameAr: "بكداش - آيس كريم حلبي", shortDescription: "أشهر آيس كريم عربي في باريس", description: "بكداش يقدم الآيس كريم الحلبي الأصيل.", category: "sweets", subcategory: "آيس كريم حلبي", country: "فرنسا", city: "باريس", address: "12 Rue des Rosiers, 75004 Paris", phone: "+33 1 42 72 91 42", email: "info@bakdash.fr", priceRange: "$", rating: "4.8", tags: "آيس كريم, حلبي, فستق", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Sultan Barber Shop", businessNameAr: "صالون السلطان للحلاقة", shortDescription: "صالون حلاقة عربي فاخر", description: "صالون السلطان يقدم خدمات الحلاقة والتجميل الرجالي.", category: "barber", subcategory: "صالون حلاقة رجالي", country: "فرنسا", city: "باريس", address: "8 Rue du Faubourg Saint-Denis, 75010 Paris", phone: "+33 1 42 38 59 27", priceRange: "$$", rating: "4.6", tags: "حلاقة, صالون, حلاقة عربية", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Bazar du Monde Arabe", businessNameAr: "سوق العالم العربي", shortDescription: "سوبرماركت عربي متكامل في باريس", description: "سوبرماركت يقدم كل المنتجات العربية والحلال.", category: "supermarket", subcategory: "سوبرماركت حلال", country: "فرنسا", city: "باريس", address: "45 Rue de Belleville, 75020 Paris", phone: "+33 1 43 58 42 61", email: "bazar@monde-arabe.fr", priceRange: "$$", rating: "4.4", tags: "سوبرماركت, حلال, منتجات عربية", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Damaskus Restaurant Berlin", businessNameAr: "مطعم دمشق - برلين", shortDescription: "مطعم دمشقي أصيل في قلب برلين", description: "مطعم يقدم الأطباق الدمشقية الأصيلة.", category: "restaurant", subcategory: "مطعم دمشقي", country: "ألمانيا", city: "برلين", address: "Sonnenallee 87, 12045 Berlin", phone: "+49 30 623 72 14", email: "info@damaskus-berlin.de", priceRange: "$$", rating: "4.6", tags: "مطعم سوري, برلين, دمشقي, منسف", status: "active", isVerified: true, isFeatured: true },
  { businessName: "Babylon Supermarkt", businessNameAr: "سوبرماركت بابل", shortDescription: "كل ما يحتاجه العرب في برلين", description: "سوبرماركت متخصص في المنتجات العربية والحلال.", category: "supermarket", subcategory: "سوبرماركت عربي", country: "ألمانيا", city: "برلين", address: "Sonnenallee 120, 12045 Berlin", phone: "+49 30 624 89 33", priceRange: "$$", rating: "4.4", tags: "سوبرماركت, حلال, عربي, برلين", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Levant Restaurant London", businessNameAr: "مطعم بلاد الشام - لندن", shortDescription: "مطعم شامي راقي في قلب لندن", description: "يقدم تجربة طعام شامية فاخرة.", category: "restaurant", subcategory: "مطعم شامي فاخر", country: "المملكة المتحدة", city: "لندن", address: "76-77 London Wall, London EC2M 5NX", phone: "+44 20 7256 1122", email: "info@levant-london.co.uk", priceRange: "$$$", rating: "4.6", tags: "مطعم شامي, لندن, فاخر, مشاوي", status: "active", isVerified: true, isFeatured: true },
  { businessName: "Edgware Road Halal Butcher", businessNameAr: "جزار الطريق الحلال", shortDescription: "جزار حلال في منطقة Edgware Road", description: "متجر لحوم حلال طازجة يومياً.", category: "butcher", subcategory: "جزار حلال", country: "المملكة المتحدة", city: "لندن", address: "142 Edgware Road, London W2 2DZ", phone: "+44 20 7723 8765", priceRange: "$$", rating: "4.5", tags: "جزار, حلال, لحم, دواجن", status: "active", isVerified: true, isFeatured: false },
  { businessName: "The Arabica Lounge", businessNameAr: "لاونج أرابيكا", shortDescription: "مقهى ولاونج عربي للشيشة في لندن", description: "لاونج يقدم الشيشة بنكهات متنوعة.", category: "shisha_lounge", subcategory: "مقهى شيشة", country: "المملكة المتحدة", city: "لندن", address: "35 Maida Vale, London W9 1RS", phone: "+44 20 7286 5492", priceRange: "$$", rating: "4.3", tags: "شيشة, مقهى, عربي, لندن", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Souk Amsterdam", businessNameAr: "سوق أمستردام", shortDescription: "مطعم ومقهى عربي في وسط أمستردام", description: "يجمع بين الأطباق العربية والمطبخ الأوروبي.", category: "restaurant", subcategory: "مطعم عربي", country: "هولندا", city: "أمستردام", address: "Utrechtsestraat 65, 1017 VJ Amsterdam", phone: "+31 20 624 52 19", email: "hello@soukamsterdam.nl", priceRange: "$$", rating: "4.5", tags: "مطعم عربي, أمستردام, مقهى", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Al-Iman Halal Market", businessNameAr: "سوق الإيمان الحلال", shortDescription: "بقالة حلال وعربية في أمستردام", description: "يقدم منتجات حلال طازجة، تمور، زيت زيتون، بهارات.", category: "supermarket", subcategory: "بقالة حلال", country: "هولندا", city: "أمستردام", address: "Bos en Lommerweg 126, 1055 ED Amsterdam", phone: "+31 20 684 83 21", priceRange: "$$", rating: "4.3", tags: "سوبرماركت, حلال, أمستردام, بقالة", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Le Sahara Restaurant", businessNameAr: "مطعم الصحراء - بروكسل", shortDescription: "مطعم مغربي جزائري في بروكسل", description: "يقدم المأكولات المغربية والجزائرية الأصيلة من الكسكس، الطاجين.", category: "restaurant", subcategory: "مطعم مغربي جزائري", country: "بلجيكا", city: "بروكسل", address: "Chaussee d'Ixelles 112, 1050 Ixelles", phone: "+32 2 512 43 68", priceRange: "$$", rating: "4.4", tags: "مطعم مغربي, بروكسل, كسكس, طاجين", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Baklava Palace Brussels", businessNameAr: "قصر البقلاوة - بروكسل", shortDescription: "حلويات تركية وعربية فاخرة", description: "أفضل أنواع البقلاوة التركية والحلويات العربية الفاخرة.", category: "sweets", subcategory: "حلويات تركية", country: "بلجيكا", city: "بروكسل", address: "Rue du Marche aux Herbes 78, 1000 Bruxelles", phone: "+32 2 217 09 83", priceRange: "$$", rating: "4.7", tags: "بقلاوة, حلويات, تركية, بروكسل", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Oriental Vienna", businessNameAr: "الشرقي - فيينا", shortDescription: "مطعم عربي عراقي في فيينا", description: "يقدم الأطباق العراقية الأصيلة من التمن والمقلوبة والكباب.", category: "restaurant", subcategory: "مطعم عراقي", country: "النمسا", city: "فيينا", address: "Praterstrasse 42, 1020 Wien", phone: "+43 1 214 22 87", priceRange: "$$", rating: "4.5", tags: "مطعم عراقي, فيينا, كباب, تمن", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Sahara Hookah Lounge Vienna", businessNameAr: "لاونج صحراء - فيينا", shortDescription: "مقهى وشيشة عربي في فيينا", description: "أجواء عربية أصيلة مع الشيشة والشاي والقهوة العربية.", category: "shisha_lounge", subcategory: "مقهى شيشة", country: "النمسا", city: "فيينا", address: "Mariahilfer Strasse 89, 1060 Wien", phone: "+43 1 597 63 42", priceRange: "$$", rating: "4.3", tags: "شيشة, فيينا, مقهى عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "El Oasis Halal Madrid", businessNameAr: "الواحة الحلال - مدريد", shortDescription: "مطعم ومقهى حلال في قلب مدريد", description: "يقدم مأكولات عربية إسبانية مدمجة بإشراف حلال كامل.", category: "restaurant", subcategory: "مطعم حلال إسباني", country: "إسبانيا", city: "مدريد", address: "Calle de Fuencarral 127, 28010 Madrid", phone: "+34 915 32 76 45", priceRange: "$$", rating: "4.4", tags: "مطعم حلال, مدريد, عربي إسباني", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Mezquita Central Halal Market", businessNameAr: "سوق المسجد المركزي الحلال", shortDescription: "بقالة حلال بالقرب من مسجد مدريد", description: "يقدم كل المنتجات الحلال والعربية.", category: "supermarket", subcategory: "بقالة حلال", country: "إسبانيا", city: "مدريد", address: "Calle de Alcala 480, 28027 Madrid", phone: "+34 913 67 22 81", priceRange: "$$", rating: "4.2", tags: "سوبرماركت حلال, مدريد, مسجد", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Sultan Restaurant Roma", businessNameAr: "مطعم السلطان - روما", shortDescription: "مطعم تركي عربي في روما", description: "يقدم المأكولات التركية والعربية من الكباب التركي والمازة.", category: "restaurant", subcategory: "مطعم تركي عربي", country: "إيطاليا", city: "روما", address: "Via Merulana 251, 00185 Roma", phone: "+39 06 770 99 182", priceRange: "$$", rating: "4.3", tags: "مطعم تركي, روما, كباب, حلال", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Oriental Bakery Stockholm", businessNameAr: "مخبز الشرق - ستوكهولم", shortDescription: "مخبز وحلويات عربية في ستوكهولم", description: "يقدم الخبز العربي الطازج والحلويات الشرقية.", category: "bakery", subcategory: "مخبز وحلويات عربية", country: "السويد", city: "ستوكهولم", address: "Odengatan 78, 113 22 Stockholm", phone: "+46 8 30 18 42", priceRange: "$", rating: "4.5", tags: "مخبز عربي, ستوكهولم, حلويات شرقية", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Al-Dar Restaurant Geneva", businessNameAr: "مطعم الدار - جنيف", shortDescription: "مطعم فلسطيني شامي في جنيف", description: "يقدم المسخن الفلسطيني والمأكولات الشامية الأصيلة.", category: "restaurant", subcategory: "مطعم فلسطيني شامي", country: "سويسرا", city: "جنيف", address: "Rue de Lausanne 48, 1202 Geneve", phone: "+41 22 731 77 93", priceRange: "$$$", rating: "4.6", tags: "مطعم فلسطيني, جنيف, مسخن, شامي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Casablanca Cafe Paris", businessNameAr: "مقهى الدار البيضاء - باريس", shortDescription: "مقهى مغربي يقدم الشاي بالنعناع", description: "مقهى مغربي أصيل يقدم الشاي المغربي والحلويات.", category: "cafe", subcategory: "مقهى مغربي", country: "فرنسا", city: "باريس", address: "18 Rue de la Huchette, 75005 Paris", phone: "+33 1 43 29 47 82", priceRange: "$", rating: "4.4", tags: "مقعى مغربي, باريس, شاي, حلويات", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Arabian Nights London", businessNameAr: "ليالي العربية - لندن", shortDescription: "مطعم عربي فاخر في Mayfair", description: "تجربة طعام عربية فاخرة في أرقى مناطق لندن.", category: "restaurant", subcategory: "مطعم عربي فاخر", country: "المملكة المتحدة", city: "لندن", address: "34 Curzon Street, London W1J 7TN", phone: "+44 20 7491 3832", priceRange: "$$$$", rating: "4.8", tags: "مطعم فاخر, لندن, Mayfair, عربي", status: "active", isVerified: true, isFeatured: true },
  { businessName: "Al-Baraka Travel Hamburg", businessNameAr: "سفر البركة - هامبورغ", shortDescription: "وكالة سفر عربية في هامبورغ", description: "تنظم رحلات الحج والعمرة والسياحة للعرب.", category: "travel_agency", subcategory: "وكالة سفر", country: "ألمانيا", city: "هامبورغ", address: "Steindamm 52, 20099 Hamburg", phone: "+49 40 284 12 39", priceRange: "$$$", rating: "4.3", tags: "وكالة سفر, حج, عمرة, هامبورغ", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Halal Barber Munich", businessNameAr: "صالون الحلاقة الحلال - ميونخ", shortDescription: "صالون حلاقة للرجال في ميونخ", description: "صالون حلاقة عربي يقدم خدماته للرجال والأطفال.", category: "barber", subcategory: "صالون حلاقة", country: "ألمانيا", city: "ميونخ", address: "Schwanthalerstrasse 155, 80339 Munchen", phone: "+49 89 545 32 18", priceRange: "$$", rating: "4.4", tags: "حلاقة, ميونخ, صالون عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Falafel King Rotterdam", businessNameAr: "ملك الفلافل - روتردام", shortDescription: "أفضل فلافل في روتردام", description: "يقدم الفلافل العربي الأصيل والشاورما والحمص.", category: "restaurant", subcategory: "مطعم فلافل", country: "هولندا", city: "روتردام", address: "Kruiskade 125, 3012 DE Rotterdam", phone: "+31 10 214 78 56", priceRange: "$", rating: "4.6", tags: "فلافل, روتردام, شاورما, حمص", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Al-Falah Mosque", businessNameAr: "مسجد الفلاح - بروكسل", shortDescription: "مسجد ومركز إسلامي في بروكسل", description: "مسجد ومركز مجتمعي يقدم خدمات دينية واجتماعية.", category: "mosque", subcategory: "مسجد ومركز إسلامي", country: "بلجيكا", city: "بروكسل", address: "Rue du Progres 323, 1030 Schaerbeek", phone: "+32 2 215 88 44", priceRange: "free", rating: "4.7", tags: "مسجد, بروكسل, مركز إسلامي, صلاة", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Zaytouna Halal Butcher Lyon", businessNameAr: "جزار الزيتونة الحلال - ليون", shortDescription: "جزار حلال في ليون", description: "يقدم لحوم حلال طازجة من لحم غنم وعجل ودواجن.", category: "butcher", subcategory: "جزار حلال", country: "فرنسا", city: "ليون", address: "Rue Moncey 17, 69002 Lyon", phone: "+33 4 78 42 19 37", priceRange: "$$", rating: "4.3", tags: "جزار حلال, ليون, لحم, دواجن", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Al-Nour Bakery Copenhagen", businessNameAr: "مخبز النور - كوبنهاغن", shortDescription: "مخبز عربي في كوبنهاغن", description: "يقدم الخبز العربي والحلويات والكنافة والبقلاوة.", category: "bakery", subcategory: "مخبز عربي", country: "الدنمارك", city: "كوبنهاغن", address: "Norrebrogade 78, 2200 Kobenhavn", phone: "+45 35 24 18 92", priceRange: "$", rating: "4.4", tags: "مخبز عربي, كوبنهاغن, حلويات", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Sham Palace Dublin", businessNameAr: "قصر الشام - دبلن", shortDescription: "مطعم سوري شامي في دبلن", description: "يقدم المأكولات الشامية الأصيلة في قلب دبلن.", category: "restaurant", subcategory: "مطعم شامي", country: "أيرلندا", city: "دبلن", address: "Capel Street 143, Dublin 1", phone: "+353 1 873 42 61", priceRange: "$$", rating: "4.5", tags: "مطعم شامي, دبلن, سوري, مشاوي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Medina Money Transfer", businessNameAr: "تحويل أموال المدينة - لندن", shortDescription: "تحويل أموال للدول العربية", description: "يقدم خدمات تحويل الأموال للدول العربية.", category: "money_transfer", subcategory: "تحويل أموال", country: "المملكة المتحدة", city: "لندن", address: "Edgware Road 201, London W2 1ES", phone: "+44 20 7723 91 44", priceRange: "$", rating: "4.2", tags: "تحويل أموال, لندن, Edgware Road", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Desert Rose Oslo", businessNameAr: "وردة الصحراء - أوسلو", shortDescription: "مطعم عربي في أوسلو", description: "يقدم المأكولات العربية والمشاوي والمازة.", category: "restaurant", subcategory: "مطعم عربي", country: "النرويج", city: "أوسلو", address: "Gronlandsleiret 25, 0190 Oslo", phone: "+47 22 17 38 56", priceRange: "$$", rating: "4.3", tags: "مطعم عربي, أوسلو, مشاوي, مازة", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Al-Huda Islamic Center", businessNameAr: "مركز الهداية - هلسنكي", shortDescription: "مركز إسلامي في هلسنكي", description: "يقدم خدمات دينية واجتماعية وتعليمية.", category: "mosque", subcategory: "مسجد ومركز إسلامي", country: "فنلندا", city: "هلسنكي", address: "Kaenkuja 1, 00500 Helsinki", phone: "+358 9 739 67 82", priceRange: "free", rating: "4.5", tags: "مسجد, هلسنكي, مركز إسلامي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Mecca Restaurant Lisbon", businessNameAr: "مطعم مكة - لشبونة", shortDescription: "مطعم حلال عربي في لشبونة", description: "يقدم المأكولات العربية الحلال.", category: "restaurant", subcategory: "مطعم عربي حلال", country: "البرتغال", city: "لشبونة", address: "Rua da Palma 258, 1100-394 Lisboa", phone: "+351 21 882 34 71", priceRange: "$$", rating: "4.4", tags: "مطعم حلال, لشبونة, عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Al-Rashid Supermarket Prague", businessNameAr: "سوبرماركت الرشيد - براغ", shortDescription: "سوبرماركت عربي في براغ", description: "يقدم المنتجات العربية والحلال والبهارات.", category: "supermarket", subcategory: "سوبرماركت عربي", country: "التشيك", city: "براغ", address: "Sokolovska 192/541, 190 00 Praha 9", phone: "+420 284 681 32 7", priceRange: "$$", rating: "4.2", tags: "سوبرماركت, حلال, براغ, منتجات عربية", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Nile Restaurant Warsaw", businessNameAr: "مطعم النيل - وارسو", shortDescription: "مطعم مصري عربي في وارسو", description: "يقدم المأكولات المصرية الأصيلة.", category: "restaurant", subcategory: "مطعم مصري", country: "بولندا", city: "وارسو", address: "Marszalkowska 99/101, 00-693 Warszawa", phone: "+48 22 622 43 78", priceRange: "$$", rating: "4.3", tags: "مطعم مصري, وارسو, كشري, فول", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Al-Quds Bakery Budapest", businessNameAr: "مخبز القدس - بودابست", shortDescription: "مخبز فلسطيني عربي في بودابست", description: "يقدم الخبز الفلسطيني والعربي الطازج.", category: "bakery", subcategory: "مخبز فلسطيني", country: "المجر", city: "بودابست", address: "Rakoczi ut 69, 1078 Budapest", phone: "+36 1 322 41 95", priceRange: "$", rating: "4.5", tags: "مخبز فلسطيني, بودابست, خبز عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Sahara Cafe Zurich", businessNameAr: "مقهى الصحراء - زيورخ", shortDescription: "مقهى ومطعم عربي في زيورخ", description: "يقدم الشاي العربي والقهوة التركية والمأكولات الخفيفة.", category: "cafe", subcategory: "مقهى عربي", country: "سويسرا", city: "زيورخ", address: "Langstrasse 215, 8005 Zurich", phone: "+41 43 488 76 22", priceRange: "$$", rating: "4.4", tags: "مقهى عربي, زيورخ, شاي, قهوة تركية", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Habibi Shisha Vienna", businessNameAr: "لاونج حبيبي - فيينا", shortDescription: "لاونج شيشة عربي عصري في فيينا", description: "لاونج عصري يقدم الشيشة بنكهات متنوعة.", category: "shisha_lounge", subcategory: "لاونج شيشة", country: "النمسا", city: "فيينا", address: "Praterstrasse 21, 1020 Wien", phone: "+43 1 214 52 88", priceRange: "$$", rating: "4.2", tags: "شيشة, لاونج, فيينا, عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Al-Masry Marseille", businessNameAr: "مطعم المصري - مرسيليا", shortDescription: "مطعم مصري أصيل في مرسيليا", description: "يقدم المأكولات المصرية من الكشري والملوخية.", category: "restaurant", subcategory: "مطعم مصري", country: "فرنسا", city: "مرسيليا", address: "63 La Canebiere, 13001 Marseille", phone: "+33 4 91 08 12 44", priceRange: "$$", rating: "4.4", tags: "مطعم مصري, مرسيليا, كشري, شاورما", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Cafe Beyrouth Nice", businessNameAr: "مقهى بيروت - نيس", shortDescription: "مقهى ومطعم لبناني في نيس", description: "يقدم المازة والمشاوي والحلويات اللبنانية.", category: "cafe", subcategory: "مقهى ومطعم لبناني", country: "فرنسا", city: "نيس", address: "12 Rue Massena, 06000 Nice", phone: "+33 4 93 87 22 11", priceRange: "$$", rating: "4.3", tags: "مطعم لبناني, نيس, مازة, مشاوي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Sham Palace Frankfurt", businessNameAr: "قصر الشام - فرانكفورت", shortDescription: "مطعم سوري شامي في فرانكفورت", description: "يقدم الأطباق الشامية من المشاوي والفتة والكبة.", category: "restaurant", subcategory: "مطعم شامي", country: "ألمانيا", city: "فرانكفورت", address: "Kaiserstrasse 52, 60329 Frankfurt am Main", phone: "+49 69 272 38 22", priceRange: "$$", rating: "4.5", tags: "مطعم شامي, فرانكفورت, مشاوي, كبة", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Sultan Supermarket Cologne", businessNameAr: "سوبرماركت السلطان - كولونيا", shortDescription: "سوبرماركت عربي في كولونيا", description: "يقدم المنتجات العربية والحلال والتمور.", category: "supermarket", subcategory: "سوبرماركت عربي", country: "ألمانيا", city: "كولونيا", address: "Venloer Str. 385, 50825 Koln", phone: "+49 221 168 91 33", priceRange: "$$", rating: "4.3", tags: "سوبرماركت, حلال, كولونيا, عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Al-Sham Sweets Stuttgart", businessNameAr: "حلويات الشام - شتوتغارت", shortDescription: "حلويات شامية فاخرة", description: "يقدم البقلاوة الشامية والكنافة النابلسية.", category: "sweets", subcategory: "حلويات شامية", country: "ألمانيا", city: "شتوتغارت", address: "Konigstrasse 45, 70173 Stuttgart", phone: "+49 711 293 84 17", priceRange: "$$", rating: "4.6", tags: "حلويات, شامية, بقلاوة, كنافة", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Manchester Halal Butcher", businessNameAr: "جزار مانشستر الحلال", shortDescription: "جزار وبقالة حلال", description: "يقدم اللحوم الحلال الطازجة والمنتجات العربية.", category: "butcher", subcategory: "جزار وبقالة حلال", country: "المملكة المتحدة", city: "مانشستر", address: "Wilmslow Road 142, Rusholme, Manchester M14 5AW", phone: "+44 161 224 55 88", priceRange: "$$", rating: "4.4", tags: "جزار حلال, مانشستر, بقالة", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Birmingham Cultural Center", businessNameAr: "مركز برمنغهام الثقافي", shortDescription: "مركز ثقافي عربي", description: "يقدم أنشطة ثقافية ودورات لغة عربية.", category: "mosque", subcategory: "مركز ثقافي عربي", country: "المملكة المتحدة", city: "برمنغهام", address: "Stratford Road 298, Birmingham B11 1AA", phone: "+44 121 766 22 44", priceRange: "free", rating: "4.5", tags: "مركز ثقافي, برمنغهام, عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Barcelona Arab Lounge", businessNameAr: "لاونج برشلونة العربي", shortDescription: "مطعم ولاونج عربي في برشلونة", description: "يقدم المأكولات العربية والشيشة.", category: "shisha_lounge", subcategory: "مطعم ولاونج عربي", country: "إسبانيا", city: "برشلونة", address: "Carrer de Mallorca 234, 08008 Barcelona", phone: "+34 934 88 12 55", priceRange: "$$", rating: "4.3", tags: "لاونج, شيشة, برشلونة, عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Milan Arabic Bakery", businessNameAr: "مخبز ميلان العربي", shortDescription: "مخبز عربي في ميلانو", description: "يقدم الخبز العربي والحلويات الشرقية.", category: "bakery", subcategory: "مخبز عربي", country: "إيطاليا", city: "ميلانو", address: "Via Paolo Sarpi 28, 20154 Milano", phone: "+39 02 349 41 88", priceRange: "$", rating: "4.4", tags: "مخبز عربي, ميلانو, خبز", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Athens Halal Restaurant", businessNameAr: "مطعم أثينا الحلال", shortDescription: "مطعم حلال عربي في أثينا", description: "يقدم المأكولات العربية والمشاوي.", category: "restaurant", subcategory: "مطعم حلال عربي", country: "اليونان", city: "أثينا", address: "Athinas Street 45, Athens 10551", phone: "+30 21 0321 88 42", priceRange: "$$", rating: "4.2", tags: "مطعم حلال, أثينا, عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Oasis Market Bucharest", businessNameAr: "سوق الواحة الحلال - بوخارست", shortDescription: "بقالة حلال وعربية", description: "يقدم المنتجات الحلال والعربية.", category: "supermarket", subcategory: "بقالة حلال عربية", country: "رومانيا", city: "بوخارست", address: "Strada Barcanesti 18, Sector 2, Bucuresti", phone: "+40 21 322 15 88", priceRange: "$$", rating: "4.3", tags: "بقالة, حلال, بوخارست, عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Budapest Arabic Cafe", businessNameAr: "مقهى بودابست العربي", shortDescription: "مقهى عربي ومطعم في بودابست", description: "يقدم القهوة العربية والشاي المغربي.", category: "cafe", subcategory: "مقهى ومطعم عربي", country: "المجر", city: "بودابست", address: "Kiraly utca 28, 1075 Budapest", phone: "+36 1 782 22 44", priceRange: "$$", rating: "4.5", tags: "مقهى, بودابست, قهوة عربية", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Andalusia Restaurant Lisbon", businessNameAr: "مطعم الأندلس - لشبونة", shortDescription: "مطعم مغربي أندلسي", description: "يقدم الكسكس والطاجين والبسطيلة.", category: "restaurant", subcategory: "مطعم مغربي أندلسي", country: "البرتغال", city: "لشبونة", address: "Rua de Sao Juliao 72, 1100-524 Lisboa", phone: "+351 21 887 65 22", priceRange: "$$$", rating: "4.6", tags: "مطعم مغربي, لشبونة, كسكس, طاجين", status: "active", isVerified: true, isFeatured: true },
  { businessName: "Oslo Arabic Barber", businessNameAr: "صالون أوسلو العربي", shortDescription: "صالون حلاقة عربي في أوسلو", description: "يقدم خدمات الحلاقة والتجميل للرجال والأطفال.", category: "barber", subcategory: "صالون حلاقة عربي", country: "النرويج", city: "أوسلو", address: "Gronland 18, 0188 Oslo", phone: "+47 22 42 18 33", priceRange: "$$", rating: "4.4", tags: "حلاقة, أوسلو, صالون عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Stockholm Arabic Supermarket", businessNameAr: "سوبرماركت ستوكهولم العربي", shortDescription: "سوبرماركت عربي متكامل", description: "يقدم كل المنتجات العربية والحلال.", category: "supermarket", subcategory: "سوبرماركت عربي متكامل", country: "السويد", city: "ستوكهولم", address: "Soderhallarna 11, 118 72 Stockholm", phone: "+46 8 669 28 44", priceRange: "$$", rating: "4.3", tags: "سوبرماركت, حلال, ستوكهولم, عربي", status: "active", isVerified: true, isFeatured: false },
  { businessName: "Copenhagen Shisha Garden", businessNameAr: "حديقة الشيشة - كوبنهاغن", shortDescription: "مقهى وشيشة عربي", description: "مقهى عربي يقدم الشيشة والشاي.", category: "shisha_lounge", subcategory: "مقهى وشيشة عربي", country: "الدنمارك", city: "كوبنهاغن", address: "Vesterbrogade 62, 1620 Kobenhavn", phone: "+45 33 21 44 88", priceRange: "$$", rating: "4.2", tags: "شيشة, كوبنهاغن, مقهى عربي", status: "active", isVerified: true, isFeatured: false }
];

export const seedRouter = createRouter({
  runSeed: publicQuery.mutation(async () => {
    const db = getDb();
    const existingCount = await db.select({ count: sql<number>`count(*)` }).from(merchants);
    const count = existingCount[0]?.count || 0;
    if (count >= 50) {
      return { success: true, message: "Already seeded!", count, alreadySeeded: true };
    }
    let inserted = 0;
    for (const merchant of merchantsData) {
      try {
        await db.insert(merchants).values({
          ...merchant,
          slug: merchant.businessName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") + "-" + Date.now() + "-" + Math.floor(Math.random() * 1000),
          createdAt: new Date(),
          updatedAt: new Date(),
        });
        inserted++;
      } catch (err) { console.error(`Failed: ${merchant.businessNameAr}`); }
    }
    return { success: true, message: `Inserted ${inserted} merchants!`, count: inserted, alreadySeeded: false };
  }),
  status: publicQuery.query(async () => {
    const db = getDb();
    const result = await db.select({ count: sql<number>`count(*)` }).from(merchants);
    return { count: result[0]?.count || 0 };
  }),
});
